#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this ("swc", "dc", "lc", or "cp")?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor traning for instance)
carpentry: "bst"

# Overall title for pages.
title: "Practical considerations for Molecular Dynamics"

# Email address, no mailto:
email: "support@tech.alliancecan.ca?Subject=[MolModSim]+Molecular+Dynamics+workshop"

# Life cycle stage of the lesson
# See this page for more details: https://cdh.carpentries.org/the-lesson-life-cycle.html
# Possible values: "pre-alpha", "alpha", "beta", "stable"
life_cycle: "stable"

episode_order:
    - '01-Force_Fields_and_Interactions'
    - '02-Fast_Methods_to_Evaluate_Forces'
    - '03-Solving_Equations_of_Motion'
    - '04-Periodic_Boundary'
    - '05-degrees-of-freedom'
    - '06-electrostatics'
    - '07-thermostats'
    - '08-barostats'
    - '09-water_models'
    - 'end_of_workshop'
    - 'S01-Force_Fields_Overview'


extras_order:
    - 'reference'
    - 'about'
    - 'design'
    - 'discuss'
    - 'figures'
    - 'guide'
    - 'author_guide'
    - 'scratch-pad'

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "lesson"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Sites.
amy_site: "https://amy.carpentries.org/"
bst_site: "https://docs.alliancecan.ca/wiki/Biomolecular_simulation"
cc_site: "https://www.alliancecan.ca"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/acenet-arc/cc-carpentries-styles.git"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# Surveys.
pre_survey: "https://carpentries.typeform.com/to/wi32rS?slug="
post_survey: "https://carpentries.typeform.com/to/UgVdRQ?slug="
instructor_pre_survey: "https://www.surveymonkey.com/r/instructor_training_pre_survey?workshop_id="
instructor_post_survey: "https://www.surveymonkey.com/r/instructor_training_post_survey?workshop_id="


# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - .vendor/
  - vendor/
  - .docker-vendor/

# Turn on built-in syntax highlighting.
highlighter: rouge
